[build]
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.10/mdbook-v0.4.10-x86_64-unknown-linux-gnu.tar.gz | tar xvz && cd book && ../mdbook build"
  publish = "book/book"
